import React, { useRef, useMemo, useState } from 'react';
import { ImageUp, X, CheckCircle2, AlertOctagon, ExternalLink, Copy, Check, Layers, FileCode, Wand2, Download, ScanLine, ArrowDownToLine, Lightbulb, Workflow } from 'lucide-react';
import { analyzeCodeStatic } from '../services/staticAnalyzer';

interface Props {
  code: string;
  label: string;
  isEditable?: boolean;
  onChange?: (val: string) => void;
  onImageUpload?: (base64: string) => void;
  onLoadDemoImage?: () => void;
  attachedImage?: string | null;
  onClearImage?: () => void;
  color?: 'blue' | 'green';
  scope?: 'snippet' | 'module';
  onScopeChange?: (scope: 'snippet' | 'module') => void;
}

export const CodeBlock: React.FC<Props> = ({ 
  code, 
  label, 
  isEditable = false, 
  onChange, 
  onImageUpload,
  onLoadDemoImage,
  attachedImage,
  onClearImage,
  color = 'blue',
  scope = 'snippet',
  onScopeChange
}) => {
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [copied, setCopied] = useState(false);
  const [highlightedLines, setHighlightedLines] = useState<number[]>([]);
  const [activeSuggestion, setActiveSuggestion] = useState<string | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const backdropRef = useRef<HTMLDivElement>(null);
  
  const borderColor = color === 'green' ? 'border-eco-500/50' : 'border-blue-500/50';
  const labelColor = color === 'green' ? 'text-eco-400' : 'text-blue-400';

  const staticCheck = useMemo(() => {
    if (!isEditable) return { isValid: true, errors: [], structuralHighlights: [], requiresDynamicTracing: false, abstractionWarnings: [] };
    return analyzeCodeStatic(code);
  }, [code, isEditable]);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file && onImageUpload) {
      const reader = new FileReader();
      reader.onloadend = () => {
        onImageUpload(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadNotebook = () => {
    // ... (Code for notebook generation same as before)
    const notebookContent = {
      nbformat: 4,
      nbformat_minor: 0,
      metadata: {
        colab: {
          provenance: [],
          authorship_tag: "EcoComputeAI_AutoGenerated"
        },
        kernelspec: {
          name: "python3",
          display_name: "Python 3"
        },
        accelerator: "GPU"
      },
      cells: [
        {
          cell_type: "markdown",
          metadata: {},
          source: [
            "# 🌿 EcoCompute AI Verification\n",
            "Auto-generated notebook to verify energy optimization results from DeepGreen Agent."
          ]
        },
        {
          cell_type: "code",
          metadata: {},
          execution_count: null,
          outputs: [],
          source: [
            "# 1. Environment Setup\n",
            "!pip install torch torchvision torchaudio\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import time\n",
            "print(f'PyTorch Version: {torch.__version__}')\n",
            "print(f'CUDA Available: {torch.cuda.is_available()}')\n",
            "if torch.cuda.is_available():\n",
            "    print(f'Device: {torch.cuda.get_device_name(0)}')"
          ]
        },
        {
          cell_type: "code",
          metadata: {},
          execution_count: null,
          outputs: [],
          source: [
            "# 2. Analyzed Code Snippet\n",
            code
          ]
        },
        {
          cell_type: "code",
          metadata: {},
          execution_count: null,
          outputs: [],
          source: [
            "# 3. Verification Run (Smoke Test)\n",
            "try:\n",
            "    # Attempt to instantiate and run a forward pass with dummy data\n",
            "    # Heuristic: Assuming standard image input (B, C, H, W)\n",
            "    model = None\n",
            "    # We try to find the last defined class in the snippet\n",
            "    import inspect\n",
            "    import sys\n",
            "    classes = [obj for name, obj in inspect.getmembers(sys.modules[__name__]) if inspect.isclass(obj) and issubclass(obj, nn.Module)]\n",
            "    if classes:\n",
            "        ModelClass = classes[-1]\n",
            "        print(f'Testing Model: {ModelClass.__name__}')\n",
            "        # Attempt instantiation with minimal args - this is best effort\n",
            "        try:\n",
            "            model = ModelClass(inplanes=64, planes=64) # Try ResNet style\n",
            "        except:\n",
            "             try:\n",
            "                 model = ModelClass(64, 64) # Try generic\n",
            "             except:\n",
            "                 print('⚠️ Could not auto-instantiate model (complex args). Please init manually.')\n",
            "        \n",
            "        if model:\n",
            "            if torch.cuda.is_available(): model = model.cuda()\n",
            "            input_tensor = torch.randn(1, 64, 56, 56)\n",
            "            if torch.cuda.is_available(): input_tensor = input_tensor.cuda()\n",
            "            \n",
            "            print('Running forward pass...')\n",
            "            start = time.time()\n",
            "            out = model(input_tensor)\n",
            "            end = time.time()\n",
            "            print(f'✅ Success! Output Shape: {out.shape}')\n",
            "            print(f'⏱️ Inference Time: {(end-start)*1000:.2f}ms')\n",
            "    else:\n",
            "        print('No nn.Module class found in snippet.')\n",
            "except Exception as e:\n",
            "    print(f'❌ Verification Error: {e}')"
          ]
        }
      ]
    };

    const blob = new Blob([JSON.stringify(notebookContent)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    
    // Create download link
    const link = document.createElement('a');
    link.href = url;
    link.download = 'EcoCompute_Verification.ipynb';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Open Colab upload page
    setTimeout(() => {
        window.open('https://colab.research.google.com/#create=true', '_blank');
    }, 1000);
  };

  const toggleHighlight = (lines: number[], suggestion: string) => {
    // If clicking same highlight, clear it. Else set it.
    if (highlightedLines.length === lines.length && highlightedLines.every((v, i) => v === lines[i])) {
      setHighlightedLines([]);
      setActiveSuggestion(null);
    } else {
      setHighlightedLines(lines);
      setActiveSuggestion(suggestion);
      // P1-2: Click-to-Scroll implementation
      if (textareaRef.current && lines.length > 0) {
        // Approximate line height for standard monospace is around 24-26px (1.625rem in tailwind)
        const lineHeight = 26;
        const targetScroll = (lines[0] - 1) * lineHeight;
        textareaRef.current.scrollTo({
            top: targetScroll,
            behavior: 'smooth'
        });
      }
    }
  };

  const handleScroll = () => {
    if (textareaRef.current && backdropRef.current) {
      backdropRef.current.scrollTop = textareaRef.current.scrollTop;
    }
  };

  return (
    <div className={`relative flex flex-col h-full rounded-xl border ${borderColor} bg-dark-900 overflow-hidden`}>
      <div className="flex items-center justify-between px-4 py-2 bg-dark-800 border-b border-gray-800">
        <div className="flex items-center gap-3">
            <span className={`text-xs font-bold tracking-wider uppercase ${labelColor}`}>{label}</span>
            {isEditable && (
                <div className={`flex items-center gap-1 px-2 py-0.5 rounded text-[10px] font-bold uppercase ${
                  !staticCheck.isValid ? 'bg-red-500/20 text-red-400' :
                  staticCheck.requiresDynamicTracing ? 'bg-purple-500/20 text-purple-400' : 'bg-green-500/20 text-green-400'
                }`}>
                    {!staticCheck.isValid ? <AlertOctagon className="w-3 h-3" /> :
                     staticCheck.requiresDynamicTracing ? <Workflow className="w-3 h-3" /> : <CheckCircle2 className="w-3 h-3" />
                    }
                    <span>
                      {!staticCheck.isValid ? "Syntax Error" :
                       staticCheck.requiresDynamicTracing ? "Dynamic Graph Detected" : "Static Scan Valid"
                      }
                    </span>
                </div>
            )}
        </div>
        
        <div className="flex items-center gap-2">
           {isEditable && onScopeChange && (
             <div className="flex bg-black/40 rounded-lg p-0.5 border border-gray-700 mr-2">
               <button 
                 onClick={() => onScopeChange('snippet')}
                 className={`px-2 py-0.5 text-[10px] flex items-center gap-1 rounded ${scope === 'snippet' ? 'bg-gray-700 text-white shadow-sm' : 'text-gray-500 hover:text-gray-300'}`}
                 title="Analyze current snippet only"
               >
                 <FileCode className="w-3 h-3" />
                 Snippet
               </button>
               <button 
                 onClick={() => onScopeChange('module')}
                 className={`px-2 py-0.5 text-[10px] flex items-center gap-1 rounded ${scope === 'module' ? 'bg-blue-600 text-white shadow-sm' : 'text-gray-500 hover:text-gray-300'}`}
                 title="Analyze as part of a larger module (Long Context)"
               >
                 <Layers className="w-3 h-3" />
                 Full Module
               </button>
             </div>
           )}

           {!isEditable && (
             <>
                <button
                  onClick={handleCopy}
                  className="flex items-center gap-1 text-xs text-gray-400 hover:text-white transition-colors px-2 py-1 rounded hover:bg-white/5"
                  title="Copy Code"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                </button>
                <button
                  onClick={handleDownloadNotebook}
                  className="flex items-center gap-1 text-xs text-gray-400 hover:text-orange-400 transition-colors px-2 py-1 rounded hover:bg-white/5"
                  title="Download .ipynb & Open Colab"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Verify (Colab)</span>
                </button>
             </>
           )}

           {isEditable && onImageUpload && (
            <>
              <input 
                type="file" 
                ref={fileInputRef} 
                onChange={handleFileChange} 
                className="hidden" 
                accept="image/*"
              />
              {onLoadDemoImage && (
                <button
                  onClick={onLoadDemoImage}
                  className="flex items-center gap-1.5 text-xs text-purple-400 hover:text-purple-300 transition-colors px-2 py-1 rounded hover:bg-purple-500/10 border border-purple-500/20 mr-1"
                  title="Use a Hand-drawn Sketch Example"
                >
                  <Wand2 className="w-3.5 h-3.5" />
                  <span className="hidden sm:inline">Demo Sketch</span>
                </button>
              )}
              <button 
                onClick={() => fileInputRef.current?.click()}
                className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white transition-colors px-2 py-1 rounded hover:bg-white/5"
                title="Upload Hand-drawn Sketch or Diagram"
              >
                <ImageUp className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">Upload Sketch</span>
              </button>
            </>
          )}
        </div>
      </div>

      <div className="flex-1 relative overflow-hidden flex flex-col group">
        {attachedImage && (
          <div className="bg-dark-800/50 border-b border-gray-800 p-2 flex items-center justify-between animate-in fade-in slide-in-from-top-2">
            <div className="flex items-center gap-2 text-xs text-gray-300">
              <div className="w-8 h-8 rounded overflow-hidden bg-black/50 border border-gray-700">
                <img src={attachedImage} alt="Reference" className="w-full h-full object-cover" />
              </div>
              <span>Diagram Attached</span>
            </div>
            {onClearImage && (
              <button onClick={onClearImage} className="text-gray-500 hover:text-red-400 p-1">
                <X className="w-4 h-4" />
              </button>
            )}
          </div>
        )}

        {isEditable ? (
          <>
            {/* Backdrop Highlight Layer */}
            <div 
                ref={backdropRef}
                className="absolute inset-0 p-4 text-sm font-mono leading-relaxed pointer-events-none overflow-hidden"
                aria-hidden="true"
            >
                {code.split('\n').map((line, i) => (
                    <div key={i} className={`${highlightedLines.includes(i + 1) ? 'bg-blue-500/30 animate-pulse shadow-[0_0_15px_rgba(59,130,246,0.3)]' : ''} w-full min-h-[1.625rem]`}>
                         {/* Render invisible text to ensure identical height/wrapping */}
                        <span className="opacity-0 select-none">{line || ' '}</span>
                    </div>
                ))}
            </div>

            <textarea
              ref={textareaRef}
              onScroll={handleScroll}
              value={code}
              onChange={(e) => onChange?.(e.target.value)}
              placeholder={scope === 'module' ? "Paste full module code here for global context analysis..." : "Paste PyTorch code snippet (or upload a sketch for visual analysis)..."}
              className="relative z-10 w-full h-full bg-transparent text-sm font-mono p-4 text-gray-300 resize-none focus:outline-none leading-relaxed"
              spellCheck={false}
            />
          </>
        ) : (
          <pre className="w-full h-full p-4 overflow-auto text-sm font-mono text-gray-300 leading-relaxed scrollbar-thin">
            <code>{code}</code>
          </pre>
        )}
        
        {isEditable && (
             <div className="absolute bottom-4 left-4 right-4 z-20 pointer-events-none">
                
                {/* Active Suggestion Popover (P1-1) */}
                {activeSuggestion && (
                   <div className="mb-2 bg-blue-900/90 border border-blue-400/50 p-3 rounded-lg backdrop-blur-md shadow-xl animate-in slide-in-from-bottom-2 pointer-events-auto">
                      <div className="flex items-start gap-2">
                        <Lightbulb className="w-4 h-4 text-yellow-400 mt-0.5 shrink-0" />
                        <div>
                          <p className="text-xs text-blue-100 font-semibold mb-1">Engineering Suggestion:</p>
                          <p className="text-xs text-blue-200/80 leading-relaxed">{activeSuggestion}</p>
                        </div>
                        <button 
                           onClick={() => {
                             setHighlightedLines([]); 
                             setActiveSuggestion(null);
                           }} 
                           className="text-blue-300 hover:text-white"
                        >
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                   </div>
                )}

                {/* New: Abstraction/Regex Warning UI */}
                {staticCheck.requiresDynamicTracing && (
                    <div className="bg-purple-900/90 border border-purple-500/50 p-2 rounded text-xs text-purple-200 backdrop-blur-md mb-2 animate-in fade-in pointer-events-auto cursor-help" title="Switching to Torch.fx or ONNX Tracing is required for full accuracy.">
                        <p className="font-bold flex items-center gap-1"><Workflow className="w-3 h-3" /> Abstraction Detected:</p>
                        <p className="opacity-80 mt-1">Regex analysis is limited. Backend will switch to <strong>Dynamic Tracing (torch.fx)</strong>.</p>
                        {staticCheck.abstractionWarnings.length > 0 && (
                            <ul className="list-disc list-inside opacity-70 mt-1 text-[10px]">
                                {staticCheck.abstractionWarnings.map((w, i) => <li key={i}>{w}</li>)}
                            </ul>
                        )}
                    </div>
                )}

                {!staticCheck.isValid && (
                    <div className="bg-red-900/90 border border-red-500/50 p-2 rounded text-xs text-red-200 backdrop-blur-md mb-2 animate-in fade-in">
                        <p className="font-bold">Pre-flight Check Failed:</p>
                        <ul className="list-disc list-inside opacity-80">
                            {staticCheck.errors.slice(0, 2).map((err, i) => <li key={i}>{err}</li>)}
                        </ul>
                    </div>
                )}
                {/* P1-1: Show Smart Highlights */}
                {staticCheck.isValid && !staticCheck.requiresDynamicTracing && staticCheck.structuralHighlights && staticCheck.structuralHighlights.length > 0 && (
                    <div className="bg-blue-900/80 border border-blue-500/30 p-2 rounded text-[10px] text-blue-200 backdrop-blur-md animate-in fade-in flex flex-wrap gap-2 pointer-events-auto">
                        <span className="font-bold uppercase opacity-70 flex items-center gap-1">
                          <ScanLine className="w-3 h-3" />
                          Smart Detect:
                        </span>
                        {staticCheck.structuralHighlights.map((h, i) => (
                            <button 
                                key={i} 
                                onClick={() => toggleHighlight(h.lineNumbers, h.suggestion)}
                                className={`
                                    px-2 py-0.5 rounded border transition-all flex items-center gap-1
                                    ${highlightedLines.length > 0 && highlightedLines[0] === h.lineNumbers[0] 
                                        ? 'bg-blue-500 text-white border-blue-400 shadow-[0_0_10px_rgba(59,130,246,0.5)]' 
                                        : 'bg-blue-500/20 border-blue-500/20 hover:bg-blue-500/40 hover:border-blue-500/50 cursor-pointer'}
                                `}
                                title={h.suggestion}
                            >
                                {h.label}
                                <span className="opacity-50 text-[9px] ml-1 flex items-center gap-0.5">
                                    <ArrowDownToLine className="w-2.5 h-2.5" />
                                    {h.lineNumbers.length} hit{h.lineNumbers.length > 1 ? 's' : ''} · L{h.lineNumbers[0]}
                                </span>
                            </button>
                        ))}
                    </div>
                )}
             </div>
        )}
      </div>
    </div>
  );
};